services:
  keycloak-server:
    image: quay.io/keycloak/keycloak:26.0.2
    container_name: keycloak-server
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://dpg-d32g543ipnbc73d5js20-a.oregon-postgres.render.com:5432/keycloak_db_yuis
      - KC_DB_USERNAME=keycloak_db_yuis_user
      - KC_DB_PASSWORD=xuj0ZjSoBD8zwKJBFMbC1Cs6SiI6cZ6q
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
    command: start-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    env_file: .env
    environment:
      - PORT=5000
    depends_on:
      keycloak-server:
        condition: service_healthy
    ports:
      - "5000:5000"
