services:
  - type: web
    name: keycloak-admin
    runtime: docker
    dockerfilePath: keycloak/Dockerfile.keycloak
    envVars:
      - key: PORT
        value: 8080
      - key: KC_HTTP_PORT
        value: 8080
      - key: KC_BOOTSTRAP_ADMIN_USERNAME
        value: admin
      - key: KC_BOOTSTRAP_ADMIN_PASSWORD
        fromSecret: keycloak_admin_password
      - key: KC_HOSTNAME
        fromService:
          type: web
          name: keycloak-admin
          property: host
      - key: KC_HOSTNAME_STRICT
        value: false
      - key: KC_CACHE
        value: local
      - key: KC_LOG_LEVEL
        value: DEBUG
      - key: KC_ADMIN_ENABLED
        value: true
      - key: KC_HTTP_ENABLED
        value: true
    healthCheckPath: /health/ready
    disk:
      name: keycloak-data
      mountPath: /opt/keycloak/data
      sizeGB: 10

secrets:
  - key: keycloak_admin_password
    value: "<your-secure-admin-password>"
