services:
  - type: web
    name: keycloak-admin
    runtime: docker
    dockerfilePath: keycloak/Dockerfile.keycloak
    plan: starter # Consider upgrading if you need more resources
    envVars:
      # Basic server configuration
      - key: PORT
        value: 8080
      - key: KC_HTTP_PORT
        value: 8080
      - key: KC_HTTP_ENABLED
        value: true
      - key: KC_HTTP_HOST
        value: 0.0.0.0
      
      # Admin user
      - key: KC_BOOTSTRAP_ADMIN_USERNAME
        value: admin
      - key: KC_BOOTSTRAP_ADMIN_PASSWORD
        value: admin # Change this to a secure password!
      
      # Database connection
      - key: KC_DB
        value: postgres
      - key: KC_DB_URL
        value: jdbc:postgresql://dpg-d32g543ipnbc73d5js20-a:5432/keycloak_db_yuis
      - key: KC_DB_USERNAME
        value: keycloak_db_yuis_user
      - key: KC_DB_PASSWORD
        value: xuj0ZjSoBD8zwKJBFMbC1Cs6SiI6cZ6q
      
      # Hostname and proxy configuration
      - key: KC_HOSTNAME
        value: ecommerce-platform-1-re24.onrender.com
      - key: KC_HOSTNAME_STRICT
        value: false
      - key: KC_PROXY
        value: edge
      
      # Cache and clustering (disabled for single instance)
      - key: KC_CACHE
        value: local
      - key: KC_CACHE_STACK
        value: local
      
      # Health and metrics
      - key: KC_HEALTH_ENABLED
        value: true
      - key: KC_METRICS_ENABLED
        value: true
      
      # Database migration and recovery - Using system properties for higher precedence
      # QUARKUS_LIQUIBASE_* variables moved to JVM system properties in startup script
      - key: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
        value: "false"
      
      # Force single-node operation - Complete clustering disable
      - key: KC_CLUSTERING
        value: "false"
      - key: JGROUPS_DISCOVERY_PROTOCOL
        value: "LOCAL"
      - key: KC_CACHE_CONFIG_FILE
        value: "cache-local.xml"

      # Additional Infinispan overrides
      - key: QUARKUS_INFINISPAN_CLIENT_DEVSERVICES_ENABLED
        value: "false"
      - key: QUARKUS_INFINISPAN_CLIENT_HOSTS
        value: "localhost:11222"

      # Disable transaction recovery to speed up startup
      - key: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
        value: "false"

      # Liquibase settings for faster startup
      - key: QUARKUS_LIQUIBASE_MIGRATE_AT_START
        value: "true"
      - key: QUARKUS_LIQUIBASE_VALIDATE_ON_MIGRATE
        value: "false"
      
      # Enhanced logging for debugging
      - key: KC_LOG_LEVEL
        value: DEBUG
      - key: QUARKUS_LOG_LEVEL
        value: INFO
      - key: QUARKUS_LOG_CATEGORY_ORG_JGROUPS_LEVEL
        value: DEBUG
      - key: QUARKUS_LOG_CATEGORY_LIQUIBASE_LEVEL
        value: DEBUG
      - key: QUARKUS_LOG_CATEGORY_ORG_KEYCLOAK_CONNECTIONS_JPA_LEVEL
        value: DEBUG
      - key: QUARKUS_LOG_CATEGORY_ORG_HIBERNATE_LEVEL
        value: INFO
      - key: QUARKUS_LOG_CATEGORY_ORG_INFINISPAN_LEVEL
        value: DEBUG
      
      # JVM options - Enhanced for debugging and single-node operation
      - key: JAVA_OPTS_APPEND
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=70.0 -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Djgroups.bind_addr=127.0.0.1 -Djgroups.tcpping.initial_hosts=127.0.0.1[7800] -Djgroups.discovery.protocol=LOCAL -Dinfinispan.cluster.name=local -Dinfinispan.node.name=single-node -Dquarkus.liquibase.migrate-at-start=true -Dquarkus.liquibase.validate-on-migrate=false -Dquarkus.liquibase.clear-checksums=true -Dkeycloak.profile=production"
    
    healthCheckPath: /health/ready
    disk:
      name: keycloak-data
      mountPath: /opt/keycloak/data
      sizeGB: 1