services:
  - type: web
    name: keycloak-admin
    runtime: docker
    dockerfilePath: keycloak/Dockerfile.keycloak
    envVars:
      - key: PORT
        value: 8080
      - key: KC_HTTP_PORT
        value: 8080
      - key: KC_BOOTSTRAP_ADMIN_USERNAME
        value: admin
      - key: KC_BOOTSTRAP_ADMIN_PASSWORD
        value: admin
      - key: KC_LOG_LEVEL
        value: INFO
      - key: KC_DB_URL
        value: jdbc:postgresql://dpg-d32g543ipnbc73d5js20-a:5432/keycloak_db_yuis
      - key: KC_DB_USERNAME
        value: keycloak_db_yuis_user
      - key: KC_DB_PASSWORD
        value: xuj0ZjSoBD8zwKJBFMbC1Cs6SiI6cZ6q
      - key: KC_HOSTNAME
        value: ecommerce-platform-1-re24.onrender.com
      - key: KC_HOSTNAME_STRICT
        value: false
      - key: KC_PROXY_HEADERS
        value: xforwarded
      - key: KC_HTTP_ENABLED
        value: true
      - key: KC_CACHE
        value: local
      - key: KC_HEALTH_ENABLED
        value: true
      - key: KC_METRICS_ENABLED
        value: true
      - key: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
        value: true
      - key: JAVA_OPTS_APPEND
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=70.0 -Djava.awt.headless=true"
    healthCheckPath: /health/ready
    disk:
      name: keycloak-data
      mountPath: /opt/keycloak/data
      sizeGB: 1
